apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p4ygyvh68-nodejs
  janus-idp.io/tekton: p4ygyvh68-nodejs
  backstage.io/kubernetes-id: p4ygyvh68-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p4ygyvh68-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
